### ISSUE TITLE
Future react native avoid main thread on iOS

### ISSUE THREAD

**Issue by emberist** [AbsaOSS/rn-indy-sdk#23]
Just for notice, using the package in iOS the console prints

`Module IndySdk requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

Hope it will be useful

**Comment by TimoGlastra** [comment]
Thanks @riccardocaranfil.

I see it currently is enabled in the [Swift side](https://github.com/AbsaOSS/rn-indy-sdk/blob/43aff51c158cb871c12ce4247aa7df74690e51da/ios/IndySdk.swift#L564-L566), but not on the objective-c side. That's why the warning is shown I believe.

I think we need to disable main queue setup as they say it is only needed when you use UIKit during init: `If your module does not require access to UIKit, then you should respond to + requiresMainQueueSetup with NO.`. 

@jakubkoci is there a specific reason main queue setup is currently required?

https://reactnative.dev/docs/native-modules-ios#implementing--requiresmainqueuesetup

**Comment by jakubkoci** [comment]
@TimoGlastra You're right. We shouldn't need access to the UI thread. I've created PR to fix this #27 

@riccardocaranfil Thanks for pointing that out 👍
